### ISSUE TITLE
xgb pickled model assumptions 

### ISSUE THREAD

**Issue by jonathanperrie** [beliveau-lab/PaintSHOP_pipeline#8]
If we want to run the blockParse_unmasked.py with separate parameters like for example formamide concentration, should we then convert our temperatures in the alternate back to the defaults originally used to get the best model we should use? 

e.g. I want to have formamide set to 42.5% rather than 50%, this would mean 7.5*0.65 ~ 5C degrees of change between temperatures, so I should use the xgb pickled model for 37C rather than the default 42C.

**Comment by brianbeliveau** [comment]
Correct. We are simply scaling temperature using the formamide correction you list, so there is little effective difference between 37ºC, 50% and 42ºC, 42.5%.
